import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#f9f5fd",
        "outline": "#76747b",
        "error-container": "#9f0519",
        "primary-fixed-dim": "#00deec",
        "inverse-on-surface": "#55545b",
        "surface-container-highest": "#25252d",
        "error-dim": "#d7383b",
        "on-tertiary-fixed": "#33002d",
        "tertiary": "#ff59e3",
        "surface-container-low": "#131319",
        "on-tertiary-fixed-variant": "#6d0061",
        "on-secondary-fixed-variant": "#6300e2",
        "on-secondary-container": "#f8f1ff",
        "primary": "#8ff5ff",
        "primary-container": "#00eefc",
        "on-primary-fixed-variant": "#005e64",
        "on-surface-variant": "#acaab1",
        "surface-container-high": "#1f1f26",
        "surface-container-lowest": "#000000",
        "outline-variant": "#48474d",
        "on-primary-fixed": "#003f43",
        "error": "#ff716c",
        "surface-dim": "#0e0e13",
        "surface-container": "#19191f",
        "inverse-surface": "#fcf8ff",
        "tertiary-dim": "#ff59e3",
        "secondary-fixed": "#dac9ff",
        "tertiary-fixed": "#ff85e4",
        "surface-variant": "#25252d",
        "on-tertiary-container": "#1b0017",
        "secondary-container": "#7000ff",
        "secondary-fixed-dim": "#ceb9ff",
        "on-error-container": "#ffa8a3",
        "background": "#0e0e13",
        "on-secondary": "#290067",
        "on-secondary-fixed": "#41009a",
        "inverse-primary": "#006a71",
        "tertiary-fixed-dim": "#ff68e3",
        "on-background": "#f9f5fd",
        "on-primary": "#005d63",
        "on-primary-container": "#005359",
        "surface-tint": "#8ff5ff",
        "surface": "#0e0e13",
        "tertiary-container": "#ff05e5",
        "primary-dim": "#00deec",
        "primary-fixed": "#00eefc",
        "secondary": "#ac89ff",
        "surface-bright": "#2c2b33",
        "secondary-dim": "#874cff",
        "on-tertiary": "#42003a",
        "on-error": "#490006",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-space-grotesk)"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
